version: '2'
services:
  server:
    environment:
      - PGPOST=postgres
      - PGPORT=5432
      - PORT=3000
    image: 'karlk15/reference-tictactoe'
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "8080:8080"
  postgres:
    image: 'postgres'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
